### ISSUE TITLE
jpeg-quality script

### ISSUE THREAD

**Issue by benkasminbullock** [dayflower/p5-Image-JPEG-EstimateQuality#2]
In the jpeg-quality script, the use line needs to be modified.

Also you should use #!/usr/bin/perl for the first line. Installed scripts have this line modified to wherever the correct Perl version lives by Build.PL.

https://github.com/benkasminbullock/p5-Image-JPEG-EstimateQuality/commit/fb5161b6901482e35d2f4a5c58a80c6d31098dc8

**Comment by dayflower** [comment]
This issue seems to refer to #1, so I'm going to close it.
Thanks for your report and patches.
